spring:
  application:
    name: Student CRUD
  profiles:
    active: default
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
      url: jdbc:mysql://localhost:3306/student
      username: root
      password: my-secret-pw